name: eclinic
description: e-Clinic Oficina da Mente

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.1"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui:
  flutter_localizations:
    sdk: flutter
  dio:
  http:
  syncfusion_flutter_datepicker:
  fl_chart: ^0.51.0
  get:
  animated_splash_screen: ^1.2.0
  loading_animation_widget:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
